### ISSUE TITLE
Release Preparation

### ISSUE THREAD

**Issue by kohdice** [kohdice/pokecli#11]
## Summary

Preparing for Release.

## Purpose

Setting up CI/CD for Release.

## Tasks

- [x] Add GitHub Actions workflow file for test
- [x] Add GitHub Actions workflow file for build
- [x] Add GitHub Actions workflow file for release
